<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Cachedecorator\Module'                    => __DIR__ . '/Module.php',
    'Cachedecorator\AbstractFactory'           => __DIR__ . '/src/Cachedecorator/AbstractFactory.php',
    'Cachedecorator\Decorator'                 => __DIR__ . '/src/Cachedecorator/Decorator.php',
    'Cachedecorator\Tests\AbstractFactoryTest' => __DIR__ . '/tests/AbstractFactoryTest.php',
    'Cachedecorator\Tests\DecoratorTest'       => __DIR__ . '/tests/DecoratorTest.php',
);
